// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZKO1xj1dxlxQxKRQOqcPYH8c17VBY1AI',
    appId: '1:795904691120:web:49aa8f3dd3ae505ce7a475',
    messagingSenderId: '795904691120',
    projectId: 'pomodoro-e05a2',
    authDomain: 'pomodoro-e05a2.firebaseapp.com',
    storageBucket: 'pomodoro-e05a2.appspot.com',
    measurementId: 'G-PB236NTQGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcBkbbSBuOsQsXcZCOBzH-cSfB_Ts7js0',
    appId: '1:795904691120:android:c19af0bed5387075e7a475',
    messagingSenderId: '795904691120',
    projectId: 'pomodoro-e05a2',
    storageBucket: 'pomodoro-e05a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMfbyuiHjg02dDTq6bmANfE4slu0PlrCk',
    appId: '1:795904691120:ios:d6eaf35c9d169f0ce7a475',
    messagingSenderId: '795904691120',
    projectId: 'pomodoro-e05a2',
    storageBucket: 'pomodoro-e05a2.appspot.com',
    iosClientId: '795904691120-mqogspuje5c9gfl77ah2s0ug8rr5ftuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMfbyuiHjg02dDTq6bmANfE4slu0PlrCk',
    appId: '1:795904691120:ios:d6eaf35c9d169f0ce7a475',
    messagingSenderId: '795904691120',
    projectId: 'pomodoro-e05a2',
    storageBucket: 'pomodoro-e05a2.appspot.com',
    iosClientId: '795904691120-mqogspuje5c9gfl77ah2s0ug8rr5ftuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoro',
  );
}
